# 数据源类型 en/cn
datasource_type: cn

# 路径
path:
    # 模型保存路径
    model_path: ./models/bilstm

# 英文
en:
    # 英文 LibriSpeech 数据集路径
    path: /home/wjunneng/Ubuntu/2019-Speech-Recognition/datasets/LibriSpeech/dev-clean
    # wav路径与label之间的分割符
    audio_label_splitter: ' '
    # 选中的txt数目
    how_many: 2


# 中文
cn:
    # 中文 LifeSpeech 数据集路径
    path: /home/wjunneng/Ubuntu/2019-Speech-Recognition/datasets/LifeSpeech
    # wav路径与label之间的分割符
    audio_label_splitter: ','
    # label文件路径
    audio_label_path: dev.txt


# token
token:
    PAD: 0
    UNK: 1
    SOS: 2
    EOS: 3
    SPACE: 4
    PAD_FLAG: '<pad>'
    UNK_FLAG: '<unk>'
    SOS_FLAG: '<sos>'
    EOS_FLAG: '<eos>'
    SPACE_FLAG: '<space>'
    # 组合
    flag_list: ['<pad>', '<unk>', '<sos>', '<eos>', '<space>']

# 模型参数
num_layers_encoder: 2
num_layers_decoder: 2
rnn_size_encoder: 450
rnn_size_decoder: 450
embedding_dim: 10
batch_size: 4
epochs: 10
use_cyclic_lr: True
learning_rate: 0.00001
max_lr: 0.00003
learning_rate_decay_steps: 700
